kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: nifi-container
        image: apache/nifi:1.9.2
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 22
          name: tcp
        - containerPort: 6065
          name: listenhttp  
        resources:
          requests:
            cpu: ".5"
            memory: "8Gi"
          limits:
            cpu: "1"
        env:
        - name: VERSION
          value: "1.9"
        - name: NIFI_CLUSTER_IS_NODE
          value: "false"
        - name: NIFI_CLUSTER_NODE_PROTOCOL_PORT
          value: "9088"