apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: efm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efm
  template:
    metadata:
      labels:
        app: efm
    spec:
      containers:
      - name: efm-container
        image: sunmanregistry.azurecr.io/efm:1.0.0.1
        ports:
        - containerPort: 10080
          name: http
        resources:
          requests:
            cpu: ".5"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        envFrom:
          - configMapRef:
             name: efm-configmap
      imagePullSecrets:
      - name: sunilesecret
---
apiVersion: extensions/v1beta1
kind: Service             #+
apiVersion: v1            #+
metadata:                 #+
  name: efm-service     #+
spec:                     #+
  selector:               #+
    app: efm            #+
  ports:                  #+
  - protocol: TCP         #+
    targetPort: 10080     #+
    port: 80           #+
    name: http            #+
  type: LoadBalancer      #+
  loadBalancerSourceRanges:
  - 0.0.0.0/0
