apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minifi-datagenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minifi-datagenerator
  template:
    metadata:
      labels:
        app: minifi-datagenerator
    spec:
      containers:
      - name: minifi-datagenerator-container
        image: sunmanregistry.azurecr.io/minifi-java:0.6.0
        ports:
        - containerPort: 10080
          name: http
        - containerPort: 6065
          name: listenhttp  
        resources:
          requests:
            cpu: ".5"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: NIFI_C2_ENABLE
          value: "true"
        - name: MINIFI_AGENT_CLASS
          value: "datagenerator"
        - name: NIFI_C2_REST_URL
          value: "http://efm-service.default.svc.cluster.local/efm/api/c2-protocol/heartbeat"
        - name: NIFI_C2_REST_URL_ACK
          value: "http://efm-service.default.svc.cluster.local/efm/api/c2-protocol/acknowledge"
        - name: JVM_ARGS_2
          value: "-Xms100m"
        - name: JVM_ARGS_3
          value: "-Xms100m"
        - name: HEARTBEAT
          value: "10000"
---
kind: Service             #+
apiVersion: v1            #+
metadata:                 #+
  name: minifi-dg-service     #+
spec:                     #+
  selector:               #+
    app: minifi-datagenerator            #+
  ports:                  #+
  - protocol: TCP         #+
    targetPort: 10080     #+
    port: 10080              #+
    name: http            #+
  - protocol: TCP         #+
    targetPort: 9877     #+
    port: 9877              #+
    name: tcpsyslog    
  - protocol: TCP         #+
    targetPort: 9878     #+
    port: 9878             #+
    name: udpsyslog             #+
  - protocol: TCP         #+
    targetPort: 6065        #+
    port: 6065              #+
    name: listenhttp             #+
  type: LoadBalancer      #+
